[package]
name = "calc"
version = "0.4.2"
edition = "2021"
[dependencies]
console      = { version = "*", default-features = false }
gnuplot      = { version = "*", default-features = false }
terminal_size= { version = "*", default-features = false }
[target.'cfg(target_os = "linux")'.dependencies]
libc         = { version = "*", default-features = false }