[package]
name = "kalc"
version = "0.5.6"
edition = "2021"
[dependencies]
gnuplot      = { version = "*", default-features = false }
[target.'cfg(not(unix))'.dependencies]
console      = { version = "*", default-features = false }
[target.'cfg(unix)'.dependencies]
libc         = { version = "*", default-features = false }