[package]
name         = "kalc"
description  = "a complex numbers, 2d/3d graphing, arbitrary precision, vector, cli calculator with real-time output"
license      = "GPL-3.0-only"
authors      = ["bgkillas <mswalhelm@gmail.com>"]
readme       = "README.md"
keywords     = ["cli","calculator"]
categories   = ["command-line-interface","command-line-utilities","mathematics"]
repository   = "https://github.com/bgkillas/kalc"
version      = "0.8.0"
edition      = "2021"

[profile.release]
codegen-units = 1
lto = true
strip = true

[dependencies]
rug          = { version = "1.19.2", default-features = false, features = ["complex","integer"] }
gnuplot      = { version = "0.0.39", default-features = false }

[target.'cfg(not(unix))'.dependencies]
console      = { version = "0.15.7", default-features = false }
term_size    = { version = "0.3.2", default-features = false }

[target.'cfg(unix)'.dependencies]
libc         = { version = "0.2.147", default-features = false }