[package]
name = "calc"
version = "0.2.6"
edition = "2021"
[dependencies]
console = { version = "*", default-features = false }
gnuplot = { version = "*", default-features = false }
[target.'cfg(target_os = "linux")'.dependencies]
libc =    { version = "*", default-features = false }