on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x86_64
          - aarch64

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Install cross-compilation dependencies
        run: rustup target add aarch64-unknown-linux-musl

      - name: Build project for ${{ matrix.os }}-${{ matrix.arch }}
        run: cargo build --release --target ${{ matrix.arch }}-unknown-linux-musl
